### ISSUE TITLE
Failed to get `fc-consensus` as a dependency of package `frontier-template-node v0.0.0

### ISSUE THREAD

**Issue by SHA888** [substrate-developer-hub/frontier-node-template#1]
I've just forked the repo and run `cargo build --release` for the first time and got `Failed to get `fc-consensus` as a dependency of package `frontier-template-node v0.0.0`

I've run `substrate-node-template` previously without problem, so I assumed the `frontier-node-template` would be work in a similar way.

What might I miss?

**Comment by NukeManDan** [comment]
I think you need to update your rust toolchain with `rustup update`.
I can confirm this builds on a fresh clone on my local machine with today's nightly and latest stable.

I am using:
```
$ rustc --version -v
rustc 1.54.0 (a178d0322 2021-07-26)
binary: rustc
commit-hash: a178d0322ce20e33eac124758e837cbd80a6f633
commit-date: 2021-07-26
host: x86_64-unknown-linux-gnu
release: 1.54.0
LLVM version: 12.0.1

$ rustc +nightly --version -v
rustc 1.56.0-nightly (2827db2b1 2021-08-01)
binary: rustc
commit-hash: 2827db2b137e899242e81f1beea39ae26e245153
commit-date: 2021-08-01
host: x86_64-unknown-linux-gnu
release: 1.56.0-nightly
LLVM version: 12.0.1
```

What are you using?

**Comment by SHA888** [comment]
Thanks @NukeManDan for the reply,
I'm using the latest toolchain as you do.

`$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/kresna/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-2021-02-24-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.54.0 (a178d0322 2021-07-26)

$ rustc --version -v
rustc 1.54.0 (a178d0322 2021-07-26)
binary: rustc
commit-hash: a178d0322ce20e33eac124758e837cbd80a6f633
commit-date: 2021-07-26
host: x86_64-unknown-linux-gnu
release: 1.54.0
LLVM version: 12.0.1

$ rustc +nightly --version -v
rustc 1.56.0-nightly (2827db2b1 2021-08-01)
binary: rustc
commit-hash: 2827db2b137e899242e81f1beea39ae26e245153
commit-date: 2021-08-01
host: x86_64-unknown-linux-gnu
release: 1.56.0-nightly
LLVM version: 12.0.1
`

**Comment by NukeManDan** [comment]
Ah! I see that `2a021f69a2db02106c82c018fac637b647a2b13c` was a commit in a now deleted branch. I have replaced it with https://github.com/paritytech/frontier/commit/76452a7e2ea7cb7e30d44c518a88104e818b2651

Please do a `git pull` from the `main` branch here to get the change, or do a find and replace in your cargo files to update. 

Does that fix things?

**Comment by SHA888** [comment]
![Screenshot from 2021-08-03 16-10-48](https://user-images.githubusercontent.com/72794806/127981416-dedfb33a-1101-4c0a-b1e0-bd9cba645bcd.png)
Somehow, git pull couldn't fix it :(

**Comment by SHA888** [comment]
I'll take a look into the cargo.toml files

**Comment by SHA888** [comment]
I've check cargo files and it compiles after update rev `2a021f69a2db02106c82c018fac637b647a2b13c` to `76452a7e2ea7cb7e30d44c518a88104e818b2651`
